exclude: ".*/data/.*|.maint/.*_author.*.py|.vscode/.*.json"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.svg'
      - id: end-of-file-fixer
        exclude: '.*\.svg'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args: [ --fix, --show-fixes ]
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        args: ["--profile", "jinja"]
      - id: djlint-django
        args: ["--profile", "jinja"]

ci:
  autoupdate_schedule: monthly
