services:
  # Migas API server
  migas-server:
    build:
      context: .
    image: "migas-server:latest"
    container_name: "migas-server"
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy
      hotmem:
        condition: service_healthy
    networks:
      - migas
    command:
      --proxy-headers --port 8080 --host 0.0.0.0 --reload --reload-dir /src
    volumes:
      - .:/src
      - /src/.venv/
    develop:
      watch:
        - action: sync
          path: .
          target: /src/
          ignore:
            - .venv/
            - .git/
            - .maint/
            - .pytest_cache/
            - .ruff_cache/
            - __pycache__/
            - dump.rdb
            - mounts/
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile
    environment:
      MIGAS_REDIS_URI: "redis://hotmem:6379"
      DATABASE_URL: "postgresql+asyncpg://postgres:crumbs@postgres:5432/migas"
      MIGAS_REQUEST_WINDOW:
      MIGAS_MAX_REQUESTS_PER_WINDOW:
      MIGAS_MAX_REQUEST_SIZE:
      MIGAS_BYPASS_RATE_LIMIT:
      MIGAS_GEOLOC:
      MIGAS_DEV: 1
      PYTEST_ADDOPTS: "-p no:cacheprovider"

  # Redis in-memory db
  hotmem:
    image: "redis:7.0.2-alpine3.16"
    container_name: "redis"
    hostname: "redis"
    restart: always
    ports:
      - "6380:6379"
    networks:
      - migas
    command: redis-server
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 10s
      retries: 1

  # Postgres persistent db
  database:
    image: "postgres:14.3-alpine3.16"
    container_name: "postgres"
    hostname: "postgres"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./mounts/db:/var/lib/postgresql/data/
      - ./deploy/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "crumbs"
      POSTGRES_DB: "migas"
    networks:
      - migas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h postgres"]
      interval: 10s
      timeout: 10s
      retries: 2

# Network to link all services
networks:
  migas:
    name: migas
