FROM python:3.10-slim
ARG BUILDTYPE=latest
ARG DEPLOYSERVER=uvicorn
ARG VERSION
ENV YARL_NO_EXTENSIONS=1 \
    MULTIDICT_NO_EXTENSIONS=1 \
    DEPLOYSERVER=${DEPLOYSERVER} \
    BUILDTYPE=${BUILDTYPE} \
    SETUPTOOLS_SCM_PRETEND_VERSION=${VERSION}
COPY . /src/
WORKDIR /src/
RUN bash deploy/docker/install.sh ${BUILDTYPE} ${DEPLOYSERVER}
ENTRYPOINT ["./deploy/docker/run.sh"]
