"""Port to ORM

Revision ID: 6d01a9e7093b
Revises:
Create Date: 2022-08-05 13:45:39.420463

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6d01a9e7093b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
