#!/bin/bash

# Common environment variables
export MIGAS_REDIS_URI='redis://localhost:6379'
export DATABASE_URL='postgresql+asyncpg://localhost/migas'
export MIGAS_DEV=1
export MIGAS_BYPASS_RATE_LIMIT=1
export MIGAS_MAX_REQUEST_SIZE=3000

if [ "$1" == "test" ]; then
    export MIGAS_DEV=1
    echo "Running in test mode..."
    uv run pytest -vrs ${2:-"migas/"}
else
    echo "Running server..."
    uvicorn migas.server.app:app \
        --host 0.0.0.0 \
        --port 8080 \
        --reload \
        --proxy-headers \
        --header X-Backend-Server:migas
fi
