#!/bin/bash

# Common environment variables
export MIGAS_REDIS_URI='redis://localhost:6379'
export DATABASE_URL='postgresql+asyncpg://localhost/migas'
export MIGAS_DEV=1
export MIGAS_BYPASS_RATE_LIMIT=1
export MIGAS_MAX_REQUEST_SIZE=3000
export MIGAS_GEOLOC=1

MAINT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export MIGAS_GEOLOC_DIR="$MAINT_DIR/../geoloc"


if [ "$1" == "test" ]; then
    export MIGAS_DEV=1
    echo "Running in test mode..."
    uv run pytest -vrs ${2:-"migas/"}
else
    echo "Running server..."
    uvicorn migas.server.app:app \
        --host 0.0.0.0 \
        --port 8080 \
        --reload \
        --reload-dir migas/server \
        --proxy-headers
fi
