name: Build and test service

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request: {}
  schedule:
  # 7am EST / 8am EDT Mondays
  - cron: '0 12 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Build the image
      run: |
        VERSION=$(uvx --with hatch-vcs hatch version | tail -n1)
        echo $VERSION
        docker compose build --build-arg BUILDTYPE=latest-test --build-arg DEPLOYSERVER=uvicorn --build-arg VERSION=$VERSION
    - name: Start all the things
      run: docker compose up -d --wait
    - name: Test the things
      run: docker exec app bash -c "pytest /src/migas/server"
    - name: Stop all the things
      run: docker compose down
